from __future__ import annotations

from dataclasses import dataclass

import torch


@dataclass(frozen=True)
class TransferProfile:
    """Condition-dependent parameter profile generated by pre-if rules."""

    cnn_weight: float
    lstm_weight: float
    material_weight: float
    dimension_weight: float
    mode_weight: float


class TransferRuleEngine:
    """
    Resolve [material_id, dimension_id, mode_id] -> transfer parameters.

    This keeps condition matching outside `network.py` so train/predict/online/batch
    all share one deterministic rule source.
    """

    def __init__(self) -> None:
        # Explicit override example requested by user: [0,0,0].
        self._explicit_profiles: dict[tuple[int, int, int], TransferProfile] = {
            (0, 0, 0): TransferProfile(
                cnn_weight=1.20,
                lstm_weight=0.85,
                material_weight=1.15,
                dimension_weight=1.10,
                mode_weight=0.95,
            ),
        }

    def _resolve_single(self, material_id: int, dimension_id: int, mode_id: int) -> TransferProfile:
        key = (int(material_id), int(dimension_id), int(mode_id))
        if key in self._explicit_profiles:
            return self._explicit_profiles[key]

        # Baseline branch preference by dimension.
        if dimension_id == 0:  # 1d
            cnn_weight = 1.10
            lstm_weight = 0.90
            dimension_weight = 1.05
        else:  # 2d
            cnn_weight = 0.90
            lstm_weight = 1.10
            dimension_weight = 1.15

        # Material-specific adjustment.
        if material_id == 0:
            material_weight = 1.00
        elif material_id == 1:
            material_weight = 1.10
        else:
            material_weight = 0.95

        # Mode-specific adjustment.
        if mode_id == 0:  # steady
            mode_weight = 0.95
        else:  # transient
            mode_weight = 1.05

        return TransferProfile(
            cnn_weight=cnn_weight,
            lstm_weight=lstm_weight,
            material_weight=material_weight,
            dimension_weight=dimension_weight,
            mode_weight=mode_weight,
        )

    def resolve_batch(
        self,
        material_id: torch.Tensor,
        dimension_id: torch.Tensor,
        mode_id: torch.Tensor,
        device: torch.device | None = None,
    ) -> torch.Tensor:
        """
        Return transfer tensor with shape [B, 5]:
        [cnn_weight, lstm_weight, material_weight, dimension_weight, mode_weight]
        """
        if material_id.ndim != 1 or dimension_id.ndim != 1 or mode_id.ndim != 1:
            raise ValueError("material_id/dimension_id/mode_id must be 1D tensors")
        if not (material_id.shape[0] == dimension_id.shape[0] == mode_id.shape[0]):
            raise ValueError("material_id/dimension_id/mode_id must have same batch size")

        target_device = device or material_id.device
        rows: list[list[float]] = []
        for m, d, mo in zip(material_id.tolist(), dimension_id.tolist(), mode_id.tolist()):
            profile = self._resolve_single(int(m), int(d), int(mo))
            rows.append(
                [
                    profile.cnn_weight,
                    profile.lstm_weight,
                    profile.material_weight,
                    profile.dimension_weight,
                    profile.mode_weight,
                ]
            )
        if not rows:
            return torch.ones((0, 5), dtype=torch.float32, device=target_device)
        return torch.tensor(rows, dtype=torch.float32, device=target_device)
